### ISSUE TITLE
 pip install -r requirements.txt

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/team-detector#3]
Collecting networkx==2.8.5 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement networkx==2.8.5 (from -r requirements.txt (line 1)) (from versions: 0.34, 0.35, 0.35.1, 0.36, 0.37, 0.99, 1.0rc1, 1.0, 1.0.1, 1.1, 1.2rc1, 1.2, 1.3rc1, 1.3, 1.4rc1, 1.4, 1.5rc1, 1.5, 1.6rc1, 1.6, 1.7rc1, 1.7, 1.8rc1, 1.8, 1.8.1, 1.9rc1, 1.9, 1.9.1, 1.10rc2, 1.10, 1.11rc1, 1.11rc2, 1.11, 2.0, 2.1, 2.2rc1, 2.2)
No matching distribution found for networkx==2.8.5 (from -r requirements.txt (line 1))

dont work

**Comment by alexemanuelol** [comment]
What python version are you using?

**Comment by C74K** [comment]
root@czakgames:~# python --version

Python 2.7.17

root@czakgames:~# python3 --version

Python 3.6.9

**Comment by alexemanuelol** [comment]
Yea, networkx Requires: Python >=3.8
Gonna add which python version that works to the readme file
