### ISSUE TITLE
how to fix this error ?

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/team-detector#4]
Could not find a version that satisfies the requirement networkx==2.8.5 (from -r requirements.txt (line 1)) (from versions: 0.34, 0.35, 0.35.1, 0.36, 0.37, 0.99, 1.0rc1, 1.0, 1.0.1, 1.1, 1.2rc1, 1.2, 1.3rc1, 1.3, 1.4rc1, 1.4, 1.5rc1, 1.5, 1.6rc1, 1.6, 1.7rc1, 1.7, 1.8rc1, 1.8, 1.8.1, 1.9rc1, 1.9, 1.9.1, 1.10rc2, 1.10, 1.11rc1, 1.11rc2, 1.11, 2.0, 2.1, 2.2rc1, 2.2)
No matching distribution found for networkx==2.8.5 (from -r requirements.txt (line 1))

**Comment by alexemanuelol** [comment]
Pretty sure it works on the tested version.

**Comment by C74K** [comment]
> Pretty sure it works on the tested version.

on windows yes on ubuntu 18 not. i dont  have arch linux.

**Comment by alexemanuelol** [comment]
Why would you want to run it on anything other than Windows? Are you playing rust on Linux?

**Comment by C74K** [comment]
no.
but linux i safer for aps like this and dont use my weak internet - run on vps

**Comment by C74K** [comment]
dont work on ubuntu.

**Comment by C74K** [comment]
cant compile on ubuntu 20.0

**Comment by alexemanuelol** [comment]
Not intended to work on linux.
